### ISSUE TITLE
mix.unifac()

### ISSUE THREAD

**Issue by azeotrope1** [gustavochm/phasepy#11]
I get in invalid syntax error on the call to the mix.unifac() function

**Comment by gustavochm** [comment]
The mix.unifac() method will fail if a group is not in the implemented database.

The available parameters are taken from the following [link ](http://www.ddbst.com/PublishedParametersUNIFACDO.html#ListOfSubGroupsAndTheirGroupSurfacesAndVolumes). Please be sure to use the same nomenclature for groups.

Please let me know if this solves your problem.

**Comment by azeotrope1** [comment]
Yes, that was is. It seems to be working fine now.
Impressive work


-----Original Message-----
