### ISSUE TITLE
Bug due to Numpy (>1.20) deprecating " np.int"

### ISSUE THREAD

**Issue by Rainjie-afk** [gustavochm/phasepy#25]
Many thanks for @gustavochm  Genius work！
When I use fit_rk model,here comes a little bug due to Numpy (>1.20) deprecating " np.int".
After many attempts, I found that the easiest way to do this is to install `pip install numpy==1.19.5`
In case others have similar problems, this issue is hereby opened.

Thanks again for @gustavochm  Genius work

**Comment by gustavochm** [comment]
Hi Rainjie! 

Thank you for your kind words! This is so simple to fix 😅 I'll do it asap.

Edit: I already uploaded an updated version to pypi. For now there is only a pre-compiled version for mac, I'll update wheels for windows shortly.

Regards,
Gustavo

**Comment by Rainjie-afk** [comment]
Glad to hear that,  looking forward！

Thanks again for your genius work.

Best regards,
Rainjie
